In [8]:
import numpy as np
passengers_age=[23,34,45,66,35,4]
parr=np.array(passengers_age)
print(parr)
print("maximum age is",parr.max())
print("minimum age is ",parr.mean())
print("average age is ", round(parr.mean()))
print("mean is:",np.median(parr))
print("standard deviation is ",parr.std())


[23 34 45 66 35  4]
maximum age is 66
minimum age is  34.5
average age is  34
mean is: 34.5
standard deviation is  18.997806890972093


In [9]:
print(passengers_age)
print(parr)

[23, 34, 45, 66, 35, 4]
[23 34 45 66 35  4]


In [10]:
parr+1
## only in nd array we can increment the value without iterating

array([24, 35, 46, 67, 36,  5])

In [11]:
import sys 
print(sys.getsizeof(5),' bytes')
## how much memory is occupied by python

28  bytes


In [12]:
import numpy as np
print(np.array([1,2,3]).itemsize,' bytes')

8  bytes


In [17]:
###speed test
import time
import numpy as np

SIZE = 10000000

A1 = range(SIZE)
A2 = range(SIZE)

L1 = np.arange(SIZE)
L2 = np.arange(SIZE)


start = time.time()
result =[x+y for x,y in zip(A1,A2)]
stop = time.time()

print('Python took ', (stop-start) * 1000, ' ms')

start = time.time()
result = L1 + L2
stop = time.time()

print('Numpy took ',(stop-start) * 1000 , ' ms')


Python took  948.8680362701416  ms
Numpy took  135.819673538208  ms


In [19]:
marks=[23, 34, 45, 66, 35, 89]
n_array=np.array(marks)
print(n_array)
print("dimension",n_array.ndim)


[23 34 45 66 35 89]
dimension 1


In [20]:
n2_array=[[23, 34, 45, 66, 35, 89],
          [56,78,57,23,89,74]]
b_array=np.array(n2_array)